# Generated by Django 6.0.7 on 2026-07-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(default=False, help_text='Driver-only: whether this driver is currently on duty and eligible to see job requests.'),
        ),
    ]
