# Generated by Django 6.0.7 on 2026-07-20 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_duration', models.DurationField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('route_snapshot', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip_summary', to='deliveries.delivery')),
            ],
        ),
    ]
