# Generated by Django 6.0.7 on 2026-07-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_alter_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='dropoff_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='dropoff_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
